baseURL = 'https://deid.it/'
title = 'DeidLab'
theme = 'hugo-coder'
languagecode = "en"
defaultcontentlanguage = "en"
paginate = 20

disqusShortname = "yourdiscussshortname"

[markup.highlight]
style = "github-dark"

[params]
  author = "Davide Ferrero"
  info = "Software & Firmware Developer"
  description = "Davide Ferrero personal website"
  keywords = "blog,developer,personal"
  avatarurl = "./img/avatar.png"
  #gravatar = "john.doe@example.com"

  faviconSVG = "./img/favicon.svg"
  favicon_32 = "./img/favicon-32x32.png"
  favicon_16 = "./img/favicon-16x16.png"

  since = 2023

  enableTwemoji = true

  colorScheme = "auto"
  hidecolorschemetoggle = false

  # customCSS = ["css/custom.css"]
  # customSCSS = ["scss/custom.scss"]
  # customJS = ["js/custom.js"]

[taxonomies]
  category = "categories"
  series = "series"
  tag = "tags"
  author = "authors"

# Social links
[[params.social]]
  name = "Github"
  icon = "fa fa-github fa-2x"
  weight = 1
  url = "https://github.com/deid84/"
# [[params.social]]
#   name = "Gitlab"
#   icon = "fa fa-gitlab fa-2x"
#   weight = 2
#   url = "https://gitlab.com/deid84/"
[[params.social]]
  name = "Linkedin"
  icon = "fa fa-linkedin fa-2x"
  weight = 3
  url = "https://www.linkedin.com/in/davideferrero/"
[[params.social]]
  name = "Telegram"
  icon = "fa fa-telegram fa-2x"
  weight = 3
  url = "https://t.me/deid84"
[[params.social]]
  name = "Youtube"
  icon = "fa fa-youtube fa-2x"
  weight = 3
  url = "https://www.youtube.com/c/deidlab"
  [[params.social]]
  name = "Medium"
  icon = "fa fa-medium fa-2x"
  weight = 3
  url = "https://medium.com/@deid84"
[[params.social]]
  name = "Mail"
  icon = "fa fa-envelope-o fa-2x"
  weight = 3
  url = "mailto:info@deid.it"

# Menu links
# [[menu.main]]
#   name = "Blog"
#   weight = 1
#   url  = "posts/"
# [[menu.main]]
#   name = "About"
#   weight = 2
#   url = "about/"